In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#numpy.array() : This function creates a new numpy array from a python list or tuple.

my_list = [1,2,3,4,5]
my_array = np.array(my_list)

print(my_array)

[1 2 3 4 5]


In [6]:
#numpy.zeros() : This function creates a new numpy arra of all zeroes with specified shape

my_zeroes = np.zeros((3,4))

my_zeroes = np.zeros((3,4),dtype='int16')
print(my_zeroes)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
#numpy.ones() : This function creates a new numpy array of all the ones specified shape

my_ones=np.ones((2,2))

print(my_ones)

[[1. 1.]
 [1. 1.]]


In [9]:
#numpy.full(): This function creates a new numpy array filled with specific value.

my_full = np.full((3,3),7)
print(my_full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
my_full = np.full((4,5),0.5)
print(my_full)

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]


In [11]:
#numpy.arrange(): Thos function creates a new numpy array with a specific range of values

my_range = np.arange(0,10,2)
print(my_range)

[0 2 4 6 8]


In [13]:
#numpy.linspace(): This function creates a new numpy array with a specified number of evenly spaced values between a start and end point.

my_linespace = np.linspace(0,1,5)

print(my_linespace)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
#np.reshape(): This function returns an array with the same data but with a new shape.

my_reshape = np.arange(6).reshape(2,3)
print(my_reshape)

[[0 1 2]
 [3 4 5]]


In [18]:
#np.transpose(): This function returns the transpose of an array.

arr = np.array([[1,2],[3,4]])
print(arr)
transpose_arr = np.transpose(arr)
print(transpose_arr)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [19]:
#np.concatenate(): This function joins two or more arrays along specified axis


arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])

concat_arr = np.concatenate((arr1,arr2),axis=0)

print(concat_arr)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
#np.sum(): returns sum of all the elements in array.


arr1 = np.array([[1,2],[3,4]])
print(arr)
sum = np.sum(arr)
print(sum)

[[1 2]
 [3 4]]
10


In [22]:
#np.max(): it will return the maximun number from the array

arr1 = np.array([[1,2],[3,4]])
max_of_arr = np.max(arr1)
print(max_of_arr)

4


In [23]:
#np.min(): This function returns the minimum value in the array

arr1 = np.array([[1,2],[3,4]])
minval =np.min(arr1)
print(minval)

1


In [25]:
#np.dot(): Thisn function returns the dot product of arrays


arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

dot_prod = np.dot(arr1,arr2)
print(dot_prod)

[[19 22]
 [43 50]]


In [27]:
#np.random.rand(): This fucntion returns an array of random values between 0 to 1 of the specified shape

rand_arr = np.random.rand(2,3)
print(rand_arr)

[[0.64082486 0.34195928 0.26129999]
 [0.73771403 0.33993317 0.2824768 ]]


In [28]:
#np.random.randint(): This function returns an array of random integers within a specified range and shape.

randint_arr = np.random.randint(1,10,size=(3,4))
print(randint_arr)

[[7 5 9 3]
 [3 1 4 2]
 [3 1 9 6]]


In [29]:
#np.where(): This function returns an array of indices where the given condition is true.

arr1 = np.array([[1,2],[3,4]])
indices = np.where(arr>2)
print(indices)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))


In [30]:
#np.unique():
arr = np.array([1,2,2,3,4,4,5,6,6,7,8,8,3,2,4,5,5,7,3,8,8])
unique_arr = np.unique(arr)
print(unique_arr)

[1 2 3 4 5 6 7 8]


In [32]:
#np.diag(): this function returns a diagonals from an array


arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
diagonal = np.diag(arr1)
print(diagonal)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [33]:
#np.argsort(): This function returns the indices that would sort an array

arr = np.array([3,1,2,4,5])
sorted_indices = np.argsort(arr)
print(sorted_indices)

[1 2 0 3 4]


In [34]:
#np.std(): this function returns the standard deviation of an array

arr = np.array([1,2,3,4,5])
std_dev= np.std(arr)
print(std_dev)

1.4142135623730951


In [35]:
#np.clip(): This function limits the value of an array within  a specified range

arr =  np.array([1,2,3,4,5])
clp = np.clip(arr,2,4)
print(clp)

[2 2 3 4 4]


In [36]:
#np.hstack(): 
#np.vstack():
#np.dstack():

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstack_arr = np.hstack((arr1, arr2))
print(hstack_arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
vstack_arr = np.vstack((arr1, arr2))
print(vstack_arr)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [38]:
#np.linalg.det(): This function returns a determinant of a square matrix

arr = np.array([[1,2],[3,4]])
det = np.linalg.det(arr)
print(det)

-2.0000000000000004


In [39]:
#np.ploy1d(): return a polynomial fn 

poly = np.poly1d([1,2,3])
print(poly)

   2
1 x + 2 x + 3


In [40]:
#np.meshgrid(): This function returns coordinate matrices from coordinate vectors



In [41]:
#np.exp():


In [43]:
#np.log():

In [ ]:
#np.histogram2d():
#np.polyfit():
#np.gredient():
#np.matmul():